Features
zied2112/HelloMicroverse pull request #1
Opened 2022-08-16 14:34 UTC by zied2112

Adding New Web pages

2022-08-16 14:56 UTC, Nemwel-Boniface requested changes
## Hello @zied2112            :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

You have done an amazing job with setting up your Hello Microverse project :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

- [ ] Kindly set the project linters so that you meet all the project requirements. You can see them by following [this](https://github.com/microverseinc/linters-config) link.
  - Then follow the first one labeled "[html&css](https://github.com/microverseinc/linters-config/blob/master/html-css)" and follow the steps provided there.

_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-16 14:56 UTC, Nemwel-Boniface commented on index.html
> +    <h1>Header 1</h1>
- [ ] Kindly note that according to the project requirements, the ```<h1>``` should have a class to style your h1.

2022-08-16 14:56 UTC, Nemwel-Boniface commented on style.css
> +}
- [ ] Kindly use the CSS class selector for styling this ```<h1>```.

2022-08-16 14:56 UTC, Nemwel-Boniface commented on .gitignore
> +test.md
- [ ] Kindly set up the project linters. Currently, I can only see the test.md file ignored but not the node_modules/.

2022-08-16 16:35 UTC, zied2112 commented
I don't know why the Stylint is not passing

2022-08-16 17:35 UTC, Nemwel-Boniface commented
Hello @zied2112 . To auto fix any linters run ```npx stylelint "**/*.{css,scss}" --fix```

2022-08-17 06:56 UTC, zied2112 commented
> Hello @zied2112 . To auto fix any linters run `npx stylelint "**/*.{css,scss}" --fix`. But following the linter errors, that should be written like this:
> 
> ```
> .header {
>   background-color: antiquewhite;
> }
> ```

I think merging and deleting this branch is not included in this project no?

2022-08-17 07:58 UTC, Nemwel-Boniface commented
@zied2112   You should only merge it when it is approved by a code reviewer. Deleting that branch once you merge it is a personal choice.

2022-08-17 10:55 UTC, zied2112 commented
and you are not the one? should I request a review?

2022-08-17 11:13 UTC, Nemwel-Boniface commented
No @zied2112  I may not be the one to review it again. When you have made the requested changes you are supposed to resubmit the link of the PR in your dashboard. Do so ASAP!

2022-08-17 13:31 UTC, Reem-lab reviewed
Hi @zied2112, 👋🏻👋🏻 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that you submit a review in the wrong activity so you should submit in the hello microverse activity in your dashoard since you are submitting it in the Portfolio first setup activity 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-08-17 13:40 UTC, zied2112 commented
> Hi @zied2112, 👋🏻👋🏻
> 
> While you made a great effort in this project, unfortunately, I cannot proceed to review your code.
> 
> ## Invalid Code Review Request
> You have submitted a project, that you submit a review in the wrong activity so you should submit in the hello microverse activity in your dashoard since you are submitting it in the Portfolio first setup activity
> 
> Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏
> 
> Cheers and Happy coding!👏👏👏
> 
> Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.
> 
> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
> 
> _Invalid Code Review Request **does not count** into the code reviews limit._

Yeah, I made a fault when I was submitting the activity. Sorry for this

2022-08-18 06:53 UTC, phelian23 approved these changes
Hi @zied2112,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-18 06:54 UTC, merged